name: bewcloud
description: "bewCloud WebDav client"
publish_to: 'none'


version: 0.0.1+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  cupertino_icons: ^1.0.6
  encrypt: ^5.0.3
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  http: ^1.2.1
  intl: ^0.19.0
  file_picker: ^8.0.0+1
  prompt_dialog: ^1.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - "assets/images/app-icon.png"
    - ".env"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"
  min_sdk_android: 21
  web:
    generate: true
    background_color: "#111111"
    theme_color: "#111111"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
